# Generated by Django 4.2.11 on 2026-03-28 18:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='store_covers/')),
                ('business_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_type', models.CharField(choices=[('afrify', 'Afrify Platform'), ('custom_domain', 'Custom Domain'), ('both', 'Both')], default='afrify', max_length=20)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()])),
                ('afrify_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('afritrade_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afrify_store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('food', 'Food & Grocery'), ('electronics', 'Electronics'), ('handmade', 'Handmade'), ('services', 'Services'), ('beauty', 'Beauty'), ('art', 'Art & Gallery'), ('auto', 'Auto'), ('bags', 'Bags'), ('jewelry', 'Jewelry'), ('books', 'Books'), ('sports', 'Sports'), ('home', 'Home & Garden'), ('wellness', 'Wellness')], max_length=50)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='template_thumbnails/')),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.IntegerField(default=100)),
                ('color_scheme', models.JSONField(default=dict)),
                ('features', models.JSONField(default=list)),
                ('is_new', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_popular', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(default='#FF6B35', max_length=7)),
                ('secondary_color', models.CharField(default='#F7931E', max_length=7)),
                ('accent_color', models.CharField(default='#004E89', max_length=7)),
                ('layout_config', models.JSONField(default=dict)),
                ('sections', models.JSONField(default=dict)),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='store_hero/')),
                ('nav_items', models.JSONField(default=list)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='stores.store')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PublishHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('error', 'Error')], max_length=20)),
                ('publish_type', models.CharField(choices=[('afrify', 'Afrify Platform'), ('custom_domain', 'Custom Domain'), ('both', 'Both')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_history', to='stores.store')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
